

name: my-GH-Act


on: 
  push:
    branches: [ master ]

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repository
        uses: actions/checkout@v1


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -la

