
name: my-GH-Act


on: 
  push:
    branches: [ master ]

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repository
        uses: actions/checkout@v1

######################################################
      # Runs a single command using the runners shell
      - name: check that everything is installed
        run: ls -la
        
      # Runs making an Artifact
      - name: make tar archive
        run: |
          tar cvf artifact.tar *
          bzip2 artifact.tar
          echo "${{ secrets.RSA_KEY_FOR_ANSIBLE_SERVER }}" > key.pem
          chmod 600 key.pem
          
        
      # Runs a single command using the runners shell  {||| cancelled |||}
      #- name: conection!!!!!
        #run: scp -oStrictHostKeyChecking=no -i key.pem artifact.tar.bz2 ubuntu@18.192.53.140:/home/ubuntu/fromgit 
        
      - name: Install requirements
        run: pip install -r requirements.txt
        ##########################################
      - uses: actions/checkout@master
      - name: Sending a message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          args: The ${{ github.event_name }} event triggered. Commit to Master branch was done successfully. All modules can be installed easily :D

#Testing part !!!!!!!
      - name: Install Apache
        run: |
          pwd
          sudo apt update
          sudo apt install apache2
          echo "GETTING ADMIN PERMS SETUP"


          sudo adduser $(whoami) www-data
          sudo adduser $(whoami) root
          sudo adduser root www-data

          sudo chown -R www-data:www-data /etc/apache2/sites-available/
          sudo chmod -R 777 /etc/apache2/sites-available/
          sudo chown -R www-data:www-data /var/www/html/
          sudo chmod -R 777 /var/www/html/

          
          ls -l /etc/apache2/sites-available/000-default.conf 
          ls -l /etc/apache2/sites-available
          ls -l /etc/apache2/
          cat /etc/apache2/sites-available/000-default.conf
          curl -I localhost
        
        






