

name: my-GH-Act


on: 
  push:
    branches: [ master ]

jobs:
  check-requirements:
    runs-on: ubuntu-latestqw

    steps:
      - name: Git clone my repository
        uses: actions/checkout@v1


      # Runs a single command using the runners shell
      - name: check that everything is installed
        run: ls -la
        
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - uses: actions/checkout@master
      - name: Sending a message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          args: The ${{ github.event_name }} event triggered. Commit to Master branch was done successfully. All modules can be installed easily :D

